### PR TITLE
Bunch of documentary and changes. Update this?

### PR DESCRIPTION
**Pull request by kylerchin**

### CODE REVIEW

**Comment by kpcyrd** [comment]
Do we really want to keep this repo? The workflow is horrible and nobody is maintaining this.

Maybe hyperboria/issues is more appropriate, since it's mostly tracking issues

**Comment by kylerchin** [comment]
@kpcyrd awesome. However, there is a big bug appearing on every OS running the latest CJDNS:

```
    1474346755 DEBUG Core.c:312 Finished getting pre-configuration from client
    1474346755 DEBUG UDPAddrIface.c:254 Binding to address [127.0.0.1:11234]
    1474346755 DEBUG UDPAddrIface.c:293 Bound to address [127.0.0.1:11234]
    1474346755 DEBUG UDPAddrIface.c:293 Bound to address [0.0.0.0:56380]
    1474346755 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]
    1474346755 INFO Configurator.c:135 Checking authorized password 0.
    1474346755 INFO Configurator.c:159 Adding authorized password #[0] for user [default-login].
    1474346760 CRITICAL Configurator.c:97 Failed to make function call [Timed out waiting for a response], error: [UDPInterface_beginConnection]
    1474346760 CRITICAL Configurator.c:57 enable Log_LEVEL=KEYS to see message content.
    1474346760 CRITICAL Configurator.c:71 Aborting.
Core exited with status [0], signal [0]
Aborted (core dumped)
```

**Comment by ansuz** [comment]
@benhylau, `android_do` conflicts.

@lgierth, thoughts on deprecating this repo? None of us have had the time/energy to maintain it.

**Comment by ansuz** [comment]
@kylerschin in the meantime, I think it's reasonable to say that this PR is entirely too large to review.

**Comment by kpcyrd** [comment]
Please comment on hyperboria/cjdns#144

**Comment by ansuz** [comment]
looks like this PR isn't going to go through.

**Comment by kylerchin** [comment]
We should use cjd's repo as main. Hyperboria org should be used for tools and extra crap.

**Comment by ansuz** [comment]
already done.

**Pull request closed without merging**
