### PR TITLE
contrib/Python fixes

### LINKED ISSUE #120: Failure to peer despite correct password, when provided by the admin interface.
My netbook and my server simply cannot peer with each other, all of a sudden. Once I went and cleaned up a bit, it appears that the netbook is providing a password that doesn't match what the server expects. But I double checked my "./contrib/python/dynamicEndpoints.py" configuration, and the conf file in the netbook does specify the correct password: an authorized password on my home server.

I checked, and dynamicEndpoints.py is reading the correct password, and the python cjdnsadmin module is bencoding the correct password, and sending it to the socket. So something in the core of cjdns itself is broken, reading the password wrong from the RPC function UDPInterface_beginConnection

Hacking interface/UDPInterface_admin.c to log the password, it is receiving the correct password inside cjdns on my netbook. It is passing the correct password to CryptoAuth_setAuth on my netbook. Then when it tries to peer with my home server... unrecognized auth.

### PR DESCRIPTION
**Pull request by MaStr**
Problem was that some parameters were not parsed correctly.

Original PR: #121
Fixed #120

commit 4e90beb6ccfb702a191cc304ec0ac067d7faf3a9
Author: Cy <nah>
Date:   Sat Apr 16 20:25:40 2016 -0700

```
Fixed broken bad cjdnsadmin.py

What the heck were they even doing with oargList...
```

commit b2e1afa2279a11b859dde76f430ff769f80f79d8
Author: Cy <nah>
Date:   Sat Apr 16 11:23:40 2016 -0700

```
forgot an exception
```

### CODE REVIEW

**Comment by MaStr** [comment]
I was also affected by that bug, and decided to fix PR #121 with the whitespace / tab issue.
Now, we can see the changes properly.

**Comment by ansuz** [comment]
As far as I can tell this looks correct, but I'd have to play with it (and the previous version) to confirm.

Does the argument parsing change the usage at all? I'd be most worried about breaking any scripts that others had built on top of the existing library.

**Comment by MaStr** [comment]
To be honest, I only took care about the tab vs whitespace conflict.
I reviewed the changes agains dynamic-endpoints.py , which did not look like a change.

As far as I understood, it is mostly changed to follow a correct ordering of a function call.

For myself, I don't have time constrains, so play around with it :) - I copied my adjustments over to the relevant nodes.

**Comment by MaStr** [comment]
Hi,
what's up with that PR? Should I issue it against cjdelisle/cjdns 

edit: ok, just saw the entrance comment. Better to do so. Don't you think it might be useful to just remove & delete the PRs from this repository? 

best regards
Matthias

**Comment by ansuz** [comment]
Yea, a PR to cjdelisle/cjdns would be best. This is just an issue tracker now. Thanks.

**Comment by MaStr** [comment]
was merged with 05a29812e7f659d9e6495f65314dac463f1d98f3 on upstream branch crashey

**Pull request closed without merging**
