### PR TITLE
Retry generating a random string for a temp file if first call fails

### PR DESCRIPTION
**Pull request by interfect**
Fixes hyperboria/cjdns#101.

### CODE REVIEW

**Comment by Kubuxu** [comment]
It would be better to do 10 retries in loop and if that fails, error out with nice message.

**Comment by lgierth** [comment]
Why does it fail in the first place?

**Comment by Kubuxu** [comment]
Probably due to low entropy.

**Comment by interfect** [comment]
Maybe? But if it's low entropy, why does it fail the first time, and then
succeed all the other times? You'd expect it to sometimes work the first
time, and sometimes fail subsequent times.

**Comment by lgierth** [comment]
I can only :+1: this pathc if we know what's going on

**Comment by interfect** [comment]
That makes sense. Unfortunately, it might take more digging into the
internals of Node that I'm willing to do.

I've thrown a bunch of Node versions at the cjdns build script on this
hardware, and they generally seem to provide broken behavior. Some of them,
for example, decide that any number converted to hex is "C", while others
crash when you ask for `os.cpus()`. I think this and the other similar
issues I opened might just come down to "Node is severely broken on
Angstrom on BBB", and should be reported there instead of here.

**Comment by interfect** [comment]
I'm just going to close this, as I really do think the problem is a badly broken node.

**Comment by Kubuxu** [comment]
Sorry that we didn't merge it, but it doesn't make much sense from the project stance. You can create your fork/branch with those things fixed but I would report all those bugs to the node devs.

**Pull request closed without merging**
