### PR TITLE
Fix map loop

### PR DESCRIPTION
**Pull request by wfleurant**

### CODE REVIEW

**Comment by lgierth** [comment]
What's this about?

**Comment by wfleurant** [comment]
We aught to test this PR here -- The first half of this PR was reverted but @madafoo added tests & fixes on request. @Kubuxu mentions map optimizations. 

https://github.com/cjdelisle/cjdns/pull/890
https://github.com/cjdelisle/cjdns/pull/889

**Comment by Kubuxu** [comment]
@wfleurant why are you PRing someone's work branch? When he is done he will PR this himself (if I am not missing here anything).

**Comment by wfleurant** [comment]
cjd reverted the first PR.. had asked madafoo for  
* [x] bugfix
* [x] testcase
* [x] works

i'm not expecting additional fixes from his branch. i think we should accept this PR because i'm the only one (afaik) who has tested it for hangs after the bugfixens.. wdyt?

**Comment by wfleurant** [comment]
We can nix this PR. I just pinged madafoo asking to make PR to hyperboria/cjdns :watch:

**Comment by wfleurant** [comment]
Reasoning for re-opening this issue:

1. https://github.com/cjdelisle/cjdns/pull/890#issuecomment-169419299
1. For fucks sake 

Ain't this PR an the reason we forked into [hyperboria/cjdns] in the first place?

**Comment by Kubuxu** [comment]
Have you addressed long test issue?

hyperboria/cjdns is supposed to be merged into cjdelisle.

**Pull request merged**
